//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fashion23.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int ID_PhanHoi { get; set; }
        public string Ten_DayDu { get; set; }
        public string Email { get; set; }
        public string TinNhan { get; set; }
        public string sdt { get; set; }
    }
}
