//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fashion23.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GioiTinh
    {
        public string Gioi_Tinh { get; set; }
        public string Ma_Sp { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
