//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fashion23.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int Id { get; set; }
        public string Ten_Sp { get; set; }
        public int IDSize { get; set; }
        public double DonGia { get; set; }
        public string Image { get; set; }
        public System.DateTime NgaySanPham { get; set; }
        public bool HangCoSan { get; set; }
        public string MoTa { get; set; }
        public int Id_NhaCungCap { get; set; }
        public int Soluong { get; set; }
        public int Views { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual Size Size { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
