//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fashion23.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Brands = new HashSet<Brand>();
            this.Customers = new HashSet<Customer>();
            this.GioHangs = new HashSet<GioHang>();
            this.GioiTinhs = new HashSet<GioiTinh>();
        }
    
        public string Ma_SP { get; set; }
        public string Ten_sp { get; set; }
        public decimal Giaban { get; set; }
        public Nullable<int> Soluong_sp { get; set; }
        public System.DateTime Ngay_tao { get; set; }
        public string Ma_Loai { get; set; }
        public string Mota_sp { get; set; }
        public string Ma_Size { get; set; }
        public string Ma_TH { get; set; }
        public string Image { get; set; }
        public string Gioi_Tinh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Brand> Brands { get; set; }
        public virtual Brand Brand { get; set; }
        public virtual Category_Product Category_Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer> Customers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GioHang> GioHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GioiTinh> GioiTinhs { get; set; }
        public virtual GioiTinh GioiTinh { get; set; }
        public virtual Size Size { get; set; }
    }
}
