//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fashion23.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shopping_Details_Cart
    {
        public string Ma_CTGH { get; set; }
        public string Ma_GH { get; set; }
        public Nullable<int> Soluong { get; set; }
        public Nullable<decimal> Tong_Thanh_Toan { get; set; }
    
        public virtual GioHang GioHang { get; set; }
    }
}
