//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fashion23
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact_Infomation
    {
        public string Dia_chi { get; set; }
        public string Sdt { get; set; }
        public string Link_FB { get; set; }
        public string Email { get; set; }
        public string Ten_KH { get; set; }
        public string Noi_Dung { get; set; }
        public string Ma_KH { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
