//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fashion23
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shopping_Cart_Details
    {
        public string Ma_CTGH { get; set; }
        public string MA_GH { get; set; }
        public Nullable<int> Soluong_SP { get; set; }
        public Nullable<decimal> Tong_ThanhToan { get; set; }
        public string Ma_SP { get; set; }
    
        public virtual GioHang GioHang { get; set; }
        public virtual Product Product { get; set; }
    }
}
